### ISSUE TITLE
Stop using CloudFlare as a public resolver

### ISSUE THREAD

**Issue by vdo** [dappnode/DNP_BIND#20]
The dnscrypt-proxy almost always chooses cloudflare as a provider because it has the lowest latency in the list, but for many reasons it is a not so good, centralizer choice.

More info: https://notabug.org/themusicgod1/cloudflare-tor

**Comment by dapplion** [comment]
Pending

**Comment by vdo** [comment]
Since there are other resolver options and CF has a great uptime, we are not putting priority in this for now.
