### ISSUE TITLE
.eth addresses not being resolved from browser

### ISSUE THREAD

**Issue by bingen** [dappnode/DNP_BIND#22]
Not sure if the problem is actually with Bind, but not sure where to open this issue.

I am connected to OpenVPN in my DAppNode. If I try to resolve in the console it works:

```
dig my.admin.dnp.dappnode.eth

; <<>> DiG 9.11.5-P4-5.1-Debian <<>> my.admin.dnp.dappnode.eth
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 48090
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: a61d6c35168273da307079ba5d1bb97a4a289548710db00a (good)
;; QUESTION SECTION:
;my.admin.dnp.dappnode.eth.	IN	A

;; ANSWER SECTION:
my.admin.dnp.dappnode.eth. 38400 IN	A	172.33.1.9

;; Query time: 1 msec
;; SERVER: 172.33.1.2#53(172.33.1.2)
;; WHEN: Tue Jul 02 22:07:22 CEST 2019
;; MSG SIZE  rcvd: 98
```

My local configuration looks good too:

```
cat /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 172.33.1.2
nameserver 1.1.1.1
nameserver 127.0.0.53
```

But if try to open http://my.admin.dnp.dappnode.eth/ (or any other `.eth` URL) in my browser (tried Firefox and Brave) it doesn't work, it says "We can’t connect to the server at my.admin.dnp.dappnode.eth"

I tried to restart both VPN and bind services in my DAppNode without luck (I'm being able to access the admin panel using the IP http://172.33.1.9

**Comment by eduadiez** [comment]
Could you review this @vdo ?

**Comment by vdo** [comment]
Hi @bingen 
By  your dig output looks like BIND is resolving properly, and also http://172.33.1.9/ is accessible, so your browser should be able to access the ADMIN site.

Can you try with curl?

`curl -v  my.dappnode > /dev/null`

and 

`curl -v  my.admin.dnp.dappnode.eth > /dev/null`

**Comment by bingen** [comment]
Hey, sorry for the late response!!

With curl isn't working either:

```
(...)
* Expire in 6 ms for 1 (transfer 0x55d71962fdd0)
* Expire in 6 ms for 1 (transfer 0x55d71962fdd0)
* Could not resolve host: my.admin.dnp.dappnode.eth
* Expire in 7 ms for 1 (transfer 0x55d71962fdd0)
* Closing connection 0
curl: (6) Could not resolve host: my.admin.dnp.dappnode.eth
```

Same for `my.dappnode`

**Comment by bingen** [comment]
Oh, I just ran last updates and now it's working! :smiley:

**Comment by vdo** [comment]
@bingen Weird and unconsistent with the dig output above, but since it is it working now and would be hard to troubleshoot, I'm closing it.

**Comment by bingen** [comment]
Yes, this is happening again:
```
$ curl -v my.dappnode > /dev/null
(...)
* Expire in 1 ms for 1 (transfer 0x562beab6af50)
* Could not resolve host: my.dappnode
* Expire in 2 ms for 1 (transfer 0x562beab6af50)
* Closing connection 0
curl: (6) Could not resolve host: my.dappnode
```
and:
```
$ curl -v my.admin.dnp.dappnode.eth > /dev/null
(...)
* Expire in 1 ms for 1 (transfer 0x564823b57f50)
* Could not resolve host: my.admin.dnp.dappnode.eth
* Expire in 2 ms for 1 (transfer 0x564823b57f50)
* Closing connection 0
curl: (6) Could not resolve host: my.admin.dnp.dappnode.eth
```
--
PS: It seems I cannot re-open this issue.
