### ISSUE TITLE
External addresses resolution

### ISSUE THREAD

**Issue by bingen** [dappnode/DNP_BIND#29]
Where is `bind` in this package getting the resolution for external addresses from? Is it possible to configure the DNS to be used for that purpose?

**Comment by vdo** [comment]
We use DNSCrypt, from 4 public servers. Check this line:
https://github.com/dappnode/DNP_BIND/blob/master/build/dnscrypt-proxy.toml#L30

What do you mean with configuring the DNS? The OpenVPN uses these transparently

**Comment by bingen** [comment]
I meant exactly this, thanks. I understand that it cannot be changed from the DAppnode dashboard, right?
Thanks!
