### ISSUE TITLE
Wrong record for dappmanager

### ISSUE THREAD

**Issue by vdo** [dappnode/DNP_BIND#6]
In `eth.hosts` the naming of the dappmanager is not consistent with the package:

https://github.com/dappnode/DNP_BIND/blob/f7cb598bba094c68a16f567700440d3f9c54f15b/build/bind/eth.hosts#L22

installer -> dappmanager

**Comment by dapplion** [comment]
The PR to solve this issue was merged and will be effective in the next version https://github.com/dappnode/DNP_BIND/pull/10
