### ISSUE TITLE
Use another public DNS provider instead of Google

### ISSUE THREAD

**Issue by vdo** [dappnode/DNP_BIND#7]
For the sake of decentralization, using only Google's DNS looks like a bad idea. We should consider using other providers, like:

- OpenNIC
- 1.1.1.1
- OpenDNS
- etc...

Maybe a combination of the above, a local OpenNIC provider(s) first and then 1.1.1.1 as a fallback.

**Comment by albpal** [comment]
Hi, I would like to solve this enhancement :dancer: I'm reviewing all your amazing work to understand how it works.

I've a question about how DNS resolution works in DAppNode. I have seen the following DockerFile:

https://github.com/dappnode/DNP_VPN/blob/master/build/Dockerfile

It already includes references to Google's DNS (8.8.8.8):
ENV VPN_DNS_SRV1 172.33.1.2
ENV VPN_DNS_SRV2 8.8.8.8


Maybe another approach is to configure docker containers with more than 1 DNS (resolv.conf uses the first DNS listed so you can set OpenNIC as the second one). Then, the BIND server you provide doesn't have to forward at all.

DockerFiles like that:
https://github.com/dappnode/DNP_VPN/blob/master/docker-compose-vpn.yml
Will have:
dns:
  - 172.33.1.2
  - 192.71.245.208 (OpenNIC DNS)
  - 87.98.175.85 (OpenNIC DNS)
  - 8.8.8.8

Would it be a valid approach?

**Comment by dapplion** [comment]
Thank you @albpal  for your contribution, pinging @vdo to take a look at it.

**Comment by vdo** [comment]
We don't want OpenNIC as a first alternative, because we need more trust in individual users of OpenNIC. Another alternatives would be [OpenDNS](https://www.opendns.com/about/anti-censorship-policy/) or 1.1.1.1.
I will ask for more 'censorship' resistant providers.

**Comment by vdo** [comment]
This should be solved with the addition of DNSCrypt-proxy
https://github.com/dappnode/DAppNode/issues/52
